# Generated by Django 4.1.4 on 2022-12-12 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=200, verbose_name='Nombre de archivo')),
                ('fecha_emitido', models.DateField(verbose_name='Fecha de emisión')),
                ('estado', models.CharField(max_length=200, verbose_name='Estado del reporte')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apirest.usuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
