# Generated by Django 4.1.4 on 2022-12-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0002_reporte'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporte',
            options={'verbose_name': 'Reporte', 'verbose_name_plural': 'Reportes'},
        ),
        migrations.AlterField(
            model_name='reporte',
            name='fecha_emitido',
            field=models.DateTimeField(verbose_name='Fecha de emisión'),
        ),
    ]
