# Generated by Django 4.1.4 on 2022-12-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=200, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('correo', models.EmailField(max_length=200, unique=True, verbose_name='Correo electronico')),
                ('password', models.CharField(max_length=200, verbose_name='Contraseña')),
                ('telefono', models.CharField(max_length=9, unique=True, verbose_name='Telefono')),
            ],
        ),
    ]
