# Generated by Django 4.1.4 on 2022-12-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0003_alter_reporte_options_alter_reporte_fecha_emitido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='fecha_emitido',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
