# Generated by Django 4.1.4 on 2022-12-10 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0004_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Administrador', 'verbose_name_plural': 'Administradores'},
        ),
    ]
