# Generated by Django 4.1.4 on 2022-12-12 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0004_alter_reporte_fecha_emitido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Reporte',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
