# Generated by Django 4.1.4 on 2022-12-11 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0006_remove_institucion_director_remove_tutor_institucion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
